# Generated by Django 4.1.2 on 2022-12-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_examcenter_examinee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExamCenter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.examcenter',),
        ),
    ]
